### ISSUE TITLE
Unknown command 'j2'

### ISSUE THREAD

**Issue by csadorf** [aiidalab/aiidalab-k8s#1]
When I ran the deploy script, it failed with

```
./deploy-jh.sh: line 12: j2: command not found`
```
because of:
https://github.com/aiidalab/aiidalab-k8s/blob/de1e7f2e58e6035c7ff65e62e606fb23404640fb/deploy-jh.sh#L12

I was a not able to determine what the `j2` executable is or how to obtain it.

**Comment by csadorf** [comment]
@ltalirz I would appreciate assistance with this issue.

**Comment by ltalirz** [comment]
Hi @csadorf , is it possible you did not `pip install -r requirements.txt`?

**Comment by csadorf** [comment]
> Hi @csadorf , is it possible you did not `pip install -r requirements.txt`?

I did, but then ran the command in a different environment. Thank you!
