### ISSUE TITLE
Folders and files gone after restarting the server

### ISSUE THREAD

**Issue by obgeneralao** [aiidalab/aiidalab-k8s#8]
Hi,

Are there any settings I have to be particular about so that the files and folders I created inside the AiiDA profile persist?
Every time I  restart the server the files and folders I created in /home/aiida got deleted.

**Comment by csadorf** [comment]
@obgeneralao You need to specify a persistent storage for your particular deployment. In our example for AWS we use the AWS-EFS storage class: https://github.com/aiidalab/aiidalab-k8s/blob/65e44242c0b5f27d64ff714e5a8eed71ca02ab26/config-template.yaml#L18-L21

I have not deployed AiiDAlab on GKE yet, but even if you don't specify a storage class, it should choose a reasonable default: https://cloud.google.com/kubernetes-engine/docs/concepts/persistent-volumes

**Comment by obgeneralao** [comment]
Hi,
It did not work for me. 
However, I was looking at the **Customize an existing Docker image** guide from the [z2j-k8s documentation](https://zero-to-jupyterhub.readthedocs.io/en/latest/jupyterhub/customizing/user-environment.html). Is it possible that aiidalab be installed/built this way?

**Comment by csadorf** [comment]
> Hi, It did not work for me. However, I was looking at the **Customize an existing Docker image** guide from the [z2j-k8s documentation](https://zero-to-jupyterhub.readthedocs.io/en/latest/jupyterhub/customizing/user-environment.html). Is it possible that aiidalab be installed/built this way?

Hi @obgeneralao , I'm not exactly sure what you mean, because [this is exactly the approach we take](https://github.com/aiidalab/aiidalab-k8s/blob/65e44242c0b5f27d64ff714e5a8eed71ca02ab26/config-template.yaml#L6-L10), no?

**Comment by obgeneralao** [comment]
Hi,
Can you take a look on my aiidalab log file and see if there is something wrong. And if you could also share your log file as well.

[aiida.log](https://github.com/aiidalab/aiidalab-k8s/files/7624837/aiida.log)

**Comment by obgeneralao** [comment]
Hi,

I got it working. I apologize for the confusion. I gave up the **ProfileList** part and just installed the Aiidalab using the installation guide here.

Thanks a lot.

**Comment by csadorf** [comment]
@obgeneralao Thanks a lot for keeping us in the loop. I think in general it would be desirable to make it work with `ProfileList` and any insight into why it may be failing would be appreciated, but I am going to assume that we can consider this particular issue here resolved.

**Comment by obgeneralao** [comment]
@csadorf 
Here are the reasons I think ```ProfileList``` does not work with the Jupyterhub's different [Docker images](https://github.com/jupyter/docker-stacks/).

- by default, ``` homeMountPath: /home/jovyan```, so if I chose the ```aiida``` profile, the notebook is launched in ```home/aiida``` directory
- If I changed ``` homeMountPath: /home```, the home folder is launched in ```/home``` but the notebook's directory is  still launched in either ```home/jovyan``` or ```home/aiida``` depending on what profile is chosen, and according to Jupyterhub's documentation on [Customizing User Environment](https://zero-to-jupyterhub.readthedocs.io/en/latest/jupyterhub/customizing/user-environment.html) "_everything a user writes to the home directory ( in this case ```/home```) will remain, and everything else will be reset in between server restarts_".

So if there is a way that the ```aiida``` profile can be launched in ```home/jovyan``` ,then that could, I think, resolve the issue

**Comment by csadorf** [comment]
> So if there is a way that the `aiida` profile can be launched in `home/jovyan` ,then that could, I think, resolve the issue

I see, you could try setting the [`SYSTEM_USER` environment variable](https://github.com/aiidalab/aiidalab-docker-stack/blob/26508db0eafbdecbce37485a84bffbe309036c29/Dockerfile#L9) to `jovyan`.
